package jo

/*
The thing you need to realize is, this library is not going to be for everyone.
Most of all, it will be for you.
So, you don't need to make it maximally flexible.
You just need to make it have the features that you want.
If that means not allowing reading arbitrary keybord input, then so be it.

Another thing we could do is, always treat it as if a controller is being used, and then behind the scenes, work out if the player is using keyboard and mouse. Meh. I don't know. Actually sure, why not. Since this game will only be for 2D games, a controller generally makes more sense anyway. So, why not?

In any case, take the rest of the day to figure this out. It seems like for this project, API design is a much bigger problem than the actual implementation.
*/

// TODO: Add all keyboard keys, or as close to that as possible.
Key :: enum u16 {
    Cancel,
    Backspace,
    Tab,
    Clear,
    Enter,

    // TODO: What should we do about the left and right version of these?
    Shift,
    Control,
    Alt,
    
    Pause,
    Caps_Lock,
    Escape,
    Space,
    Page_Up,
    Page_Down,
    End,
    Home,
    Left,
    Right,
    Down,
    Up,
    Select,
    Print,
    Execute,
    Print_Screen,
    Insert,
    Delete,
    Help,
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Left_Logo,
    Right_Logo,
    Apps,
    Sleep,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    Multiply,
    Add,
    Separator,
    Subtract,
    Decimal,
    Divide,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Num_Lock,
    Scroll,
    Volume_Mute,
    Volume_Down,
    Volume_Up,
    Comma,
    Period,
}